name: Build Userscripts
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  build-userscripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check code style
        run: |
          yarn run fmt
          git --no-pager diff --exit-code

      - name: CI tests
        run: yarn run test

      - name: Build
        run: yarn run webpack

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/userscript-out
          publish_branch: userscript-out
